# Generated by Django 4.2.6 on 2023-11-11 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHospitalSystem', '0002_remove_historicalsensor_list_int_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator_list',
            name='activation_condition',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalactuator_list',
            name='activation_condition',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
