# Generated by Django 4.2.6 on 2023-11-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHospitalSystem', '0004_actuator_list_turn_on_when_exceeded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsensor_list_int',
            name='details',
            field=models.CharField(default='-', max_length=500),
        ),
        migrations.AddField(
            model_name='sensor_list_int',
            name='details',
            field=models.CharField(default='-', max_length=500),
        ),
    ]
