# Generated by Django 4.2.6 on 2023-11-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHospitalSystem', '0006_alter_actuator_list_sensor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator_list',
            name='Data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalactuator_list',
            name='Data',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
