# Generated by Django 4.2.7 on 2023-11-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHospitalSystem', '0007_alter_actuator_list_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalsensor_list_int',
            name='details',
        ),
        migrations.RemoveField(
            model_name='sensor_list_int',
            name='details',
        ),
    ]
