# Generated by Django 4.2.7 on 2023-11-23 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHospitalSystem', '0010_actuator_list_activation_condition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actuator_list',
            name='activation_condition',
        ),
        migrations.RemoveField(
            model_name='actuator_list',
            name='threshold',
        ),
        migrations.RemoveField(
            model_name='actuator_list',
            name='turn_on_when_exceeded',
        ),
        migrations.RemoveField(
            model_name='historicalactuator_list',
            name='activation_condition',
        ),
        migrations.RemoveField(
            model_name='historicalactuator_list',
            name='threshold',
        ),
        migrations.RemoveField(
            model_name='historicalactuator_list',
            name='turn_on_when_exceeded',
        ),
    ]
