# Generated by Django 4.2.7 on 2023-11-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHospitalSystem', '0012_remove_actuator_list_sensor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actuator_list',
            name='Data',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalactuator_list',
            name='Data',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
