# Generated by Django 4.2.7 on 2023-12-06 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SmartHospitalSystem', '0014_historicalactuatorsensordata_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalActuatorSensorData',
        ),
        migrations.DeleteModel(
            name='HistoricalHistoricalActuatorSensorData',
        ),
    ]
